---
- name: Apply common setup to all VMs
  hosts: all
  become: true
  roles:
    - common

- name: Deploy frontend (vm-web)
  hosts: web
  become: true
  roles:
    - web

- name: Deploy backend (vm-api)
  hosts: api
  become: true
  roles:
    - api
